### ISSUE TITLE
Info version .Net  in client

### ISSUE THREAD

**Issue by Jh0nW1cK** [NYAN-x-CAT/Lime-RAT#29]
This does not refer to a fault, but a request. 

If it is possible to show information about the highest .net version that exists in the client. 
This can help us when making updates and using other .net tools. 

Thanks for your work, planned to make a donation.

**Comment by Jh0nW1cK** [comment]
Hi @NYAN-x-CAT, today I have made an update and several clients have not been lost, without a doubt it is because those clients were net 2.0. 

This can be avoided if a field is not displayed in the main panel indicating whether the client is 2.0 or 4.0. 

Another possibility is that the order is not executed if the client is 2.0 and the update is 4.0, or vice versa.

I hope you will consider it for the next update.

Best regards

**Comment by NYAN-x-CAT** [comment]
Hello @Jh0nW1cK 

There is a big difference between a client doesn't connect back after an update, and a client doesn't connect back after closing server.

However, your issue seems to be after an update, there are so many reasons for that, I will explain the two most common issues:
 1.the client was detected by AV
2. .NET compatibility. But you can always check the installed framework using "Details".

Also since this project is an open source, You can always change the listview columns with whatever you need. and as I said, the "Installed framework" method is already including in the project.

**Comment by Jh0nW1cK** [comment]
Hi @NYAN-x-CAT,

Of course this does not have nothing to do with a problem off with the server. 

Only has relation to the version .Net installed on the client and to facilitate the update. 
I know that may be versions of. net installed with the order" System Details", but check with each client take a long time. 

Since the builder allows .net 2 and 4, I think if this option comes default in the main panel would be very useful.

**Comment by Jh0nW1cK** [comment]
Thanks for the update in the new version
