### ISSUE TITLE
Please help. Don't connect

### ISSUE THREAD

**Issue by altimt** [NYAN-x-CAT/Lime-RAT#40]
The server does not see any clients. Even on localhost. I do everything according to the instructions. I'm building new-client.exe, I registered ip in pastebin but the server still completely refuses to see the client. I run the server on windows 2012 server. Client on win7 / 10

**Comment by NYAN-x-CAT** [comment]
If server can't work on localhost, then you have a problem.
Try compiled version instead of download source code.

**Comment by altimt** [comment]
Yes indeed. The compiled version works. But in the source code, I absolutely did not change anything. I work in VS 2017. It is true that during the construction of the solution it issues warnings.

**Comment by altimt** [comment]
And further. On win10 (not virtual) for some reason the client does not start. That is, it stops working almost instantly

**Comment by altimt** [comment]
I found one bug (though I'm not sure that it can be called a bug)
If you select Lime Ransomware in the window for selecting the message to be sent and selecting wallpaper, if you press the wallpaper selection and do not select anything (just press cancel), and then press send, an error pops up.

**Comment by NYAN-x-CAT** [comment]
Hello @altimt 

The software was fully tested on Windows 10, However, you need to disable windows defender services, Or use Windows 7 since it has no defender build-in.

And as you said, the Compiled version is working, If you want to use the source code then you must be of VS environment and how does it work.

Thanks for reporting the Ransomware windows issue.

**Comment by altimt** [comment]
Thank you, for help
