### ISSUE TITLE
why i tried but only 5-6 cilents

### ISSUE THREAD

**Issue by Satan-ilove-u** [NYAN-x-CAT/Lime-RAT#48]
why i tried but only 5-6 cilents showing i tried to uninstall one and another client shows my client is total of 300+

**Comment by R3verseCha0s** [comment]
Hello, I think that the your problem is that you don't have enough resources, The theme used by limerat is quite heavy, and some other people had mentioned about having similar issues. Please give us more information regarding your PC/VPS specs whether you use a Virtual Machine etc. If you want to try something, try removing the theme (download the code and compile without the theme.) 
Regards

**Comment by NYAN-x-CAT** [comment]
Hello @Satan-ilove-u 
Could you explain your problem again? From what I understand, you have clients and they disappeared? There are so many scenarios for this, and mostly it's user fault, not the program itself.
However, You may check your client.exe on vmware, run it then restart the PC to make sure you did check "install" option. Also make sure your IP hasn't changed.

**Comment by Satan-ilove-u** [comment]
there is showing up but limit is 5-6?

**Comment by NYAN-x-CAT** [comment]
@Satan-ilove-u 
There is no limits.

**Comment by Satan-ilove-u** [comment]
im scared that one day all my clients is gone >:-| why pastebin bro? is pastebin is really safe?

**Comment by NYAN-x-CAT** [comment]
@Satan-ilove-u it's just a pointer.
